TOP = ../../..
include $(TOP)/mk/boilerplate.mk
-include opts.mk
include $(TOP)/mk/target.mk

SRCS = Main.hs

SRC_RUNTEST_OPTS += +RTS -K32M -RTS

FAST_OPTS = 1000000
NORM_OPTS = 1000000
SLOW_OPTS = 1000000