TOP = ../../..
PROG = linear
SRCS = Utils.lhs Densematrix.lhs AbsDensematrix.lhs Matrix.lhs Misc.lhs \
       Input.lhs Cg.lhs AbsCg.lhs Matlib.lhs Absmatlib.lhs Main.lhs
include $(TOP)/nofib/mk/nofib.mk
