TOP = ../..
include $(TOP)/mk/boilerplate.mk
SUBDIRS = FilterMap-MapFilterCompose Iterate-MapIterate LengthConcat-SumMapLength Map-JoinComposeReturn MapAppend-AppendMapMap MapCompose-ComposeMapMap MapConcat-ConcatMapMap

include $(TOP)/mk/target.mk
