HC = ghc-0.22
# CFLAGS = -Wall
CFLAGS = -Wall -O -fvia-C -O2-for-C

bp:	BpGen.o ReadLists.o Main.o
	$(HC) $(CFLAGS) -syslib hbc -o bp Main.o ReadLists.o BpGen.o
	strip bp
	chmod 700 bp

ReadLists.o:	ReadLists.lhs
	$(HC) $(CFLAGS) -c ReadLists.lhs

BpGen.o:	BpGen.lhs
	$(HC) $(CFLAGS) -syslib hbc -c BpGen.lhs

Main.o:	Main.lhs
	$(HC) $(CFLAGS) -syslib hbc -c Main.lhs

clean:
	rm -f *.o *.hi bp
	cp BpGen.lhs BpGen.bak
	cp ReadLists.lhs ReadLists.bak
	cp Main.lhs Main.bak
