TOP = ../..
include $(TOP)/mk/boilerplate.mk

# Arguments for the test program
PROG_ARGS = holzhausen.prob

# 	Other problems
# ellerman.prob heathcote3.prob kidson.prob marin.prob \
# 		simple.prob fridlizius.prob holzhausen.prob \
#		kohtz.prob shinkman.prob wurzburg.prob

include $(TOP)/mk/target.mk

