TOP = ..
include $(TOP)/mk/boilerplate.mk

# ToDo: fix these subdir: cfd dcbm linsolv
SUBDIRS =  par001 pfib ray prsa soda soda7 coins minimax \
          parfact bom NESL

include $(TOP)/mk/target.mk


