TOP = ..
include $(TOP)/mk/boilerplate.mk

SUBDIRS = parfib partree sumeuler matmult ray gray prsa mandel queens coins

# CPP SYMBOLS
#
#  -DSTRATEGIES_2  to use the version 2 strategies library (default is 3)

# partak: program needs work to make it parallel

# --------------
# Old benchmarks we need to either update or kill:
# 
# bom: bill of materials?
# par001: looks like a test, not a benchmark
# coins: needs updating
# parfact: parallel factorial
# soda, soda7: small word-search algorithm
# minimax: looks like it was written for GRIP, needs a lot of updating
# NESL: a collection of benchmarks based on NESL examples
# --------------

include $(TOP)/mk/target.mk
