TOP = ../../..
PROG = bspt
SRCS = Stdlib.lhs Rationals.lhs Libfuns.lhs Params.lhs  GeomNum.lhs \
       MGRlib.lhs Euclid.lhs EuclidGMS.lhs BSPT.lhs Init.lhs \
       Interpret.lhs Input.lhs Merge.lhs Render.lhs Interface.lhs \
       Prog.lhs Main.lhs       
include $(TOP)/nofib/mk/nofib.mk
