TOP = ../../..
PROG = bspt

SRCS = BSPT.lhs Euclid.lhs EuclidGMS.lhs GeomNum.lhs Init.lhs \
       Input.lhs Interface.lhs Interpret.lhs Libfuns.lhs MGRlib.lhs \
       Main.lhs Merge.lhs Params.lhs Prog.lhs Rationals.lhs \
       Render.lhs Stdlib.lhs

include $(TOP)/nofib/mk/nofib.mk
