TOP = ../..
include $(TOP)/mk/boilerplate.mk

# Override default SRCS; the default is all source files, but
# we don't want to include paraffins.c
SRCS=Main.hs

FAST_OPTS = 500
NORM_OPTS = 1200
SLOW_OPTS = 1200

include $(TOP)/mk/target.mk

