TOP = ../../..
PROG = hpg
SRCS = Config.lhs Types.lhs Env.lhs Utils.lhs GenVal.lhs \
       GenExp.lhs GenType.lhs Main.lhs 
EXTRA_RUNTESTFLAGS = -RTS -nt 8 -dt 6 -nv 15 -dv 8 -de 8
include $(TOP)/nofib/mk/nofib.mk
