TOP = ../../..
include $(TOP)/mk/boilerplate.mk

SRC_HC_OPTS += -cpp -fglasgow-exts -H80M

# not suitable for the fast/norm/slow treatment: GHC optimises
# the repeatition away.

include $(TOP)/mk/target.mk


SRC_SUPERCOMP_HC_OPTS =
