TOP = ../..
include $(TOP)/mk/boilerplate.mk

SUBDIRS= comp_lab_zift wave4main wang typecheck transform \
solid sched nucleic2 parstof listcopy listcompr ida genfft fft \
event

SRC_MKDEPENDHS_OPTS=-fglasgow-exts

include $(TOP)/mk/target.mk

