# $Id: Makefile,v 1.2 1996/11/26 14:39:54 dnt Exp $

TOP = ../../..

SUBDIRS = comp_lab_zift event fft genfft ida listcompr listcopy \
  nucleic2 parstof sched solid transform typecheck wang wave4main

include $(TOP)/nofib/mk/nofib.mk
