HASKELL = nnhbc
CPPFLAGS +=  -I$(OPENWINHOME)/include
LDLIBS +=  -L$(OPENWINHOME)/lib -lxview -lolgx  -lX11
LINTS += -I$(OPENWINHOME)/include
CC = cc
XVI = /home/valentine/ss/Haskell/xvi/xvilib.o


fish:		Main.o $(XVI)
		$(HASKELL) Vector.o Fish_lines.o Fun_geom.o Main.o $(XVI) -o fish

xdrw:		xdrw.c
		$(CC) $(CPPFLAGS) xdrw.c $(LDLIBS)  -o xdrw

Fish_lines.o:	Vector.o

Fun_geom.o:	Fish_lines.o

Main.o:		Fish_lines.o Fun_geom.o

%.o:		%.hs
		$(HASKELL) -c $< 


