TOP = ..
include $(TOP)/mk/boilerplate.mk

SUBDIRS = \
	sieve \
	stm001 \
	callback001 \
	threads001 \
	threads003

# later:
#  stm02

# Not a good benchmark, can go really slowly for random reasons:
#  threads002

include $(TOP)/mk/target.mk

