TOP = ../../..
PROG = hidden
SRCS = Numbers.hs Vectors.hs EdgePlate.hs Matrices.hs Rotate.lhs \
       Geometric.hs MyIO.hs Solve.hs Postscript.hs Preds.hs Cross.hs \
       Comparing.hs Memo.hs Hide.hs Main.hs
EXTRA_RUNTESTFLAGS = -o1 hidden.stdout2 -o1 hidden.stdout3 objects/four.plate
include $(TOP)/nofib/mk/nofib.mk
