TOP = ..
include $(TOP)/mk/boilerplate.mk
#SUBDIRS = compile-time contracts ilya jason neil peter toys
# The ilya tests are for program equivalence
SUBDIRS = neil peter toys

include $(TOP)/mk/target.mk
