TOP = ../../..
PROG = cfd
SRCS = Norm.hs S_Array.hs Defs.hs Quad_def.hs L_matrix.hs C_matrix.hs \
       S_matrix.hs Jcb_method.hs Chl_method_q.hs TG_iter.hs Gen_net.hs \
       Data8.hs Main.hs
include $(TOP)/nofib/mk/nofib.mk
