TOP = ../..
include $(TOP)/mk/boilerplate.mk
include $(TOP)/mk/target.mk

FAST_OPTS = [a-j][a-j][a-j][0-9][p-z]
NORM_OPTS = [a-j][a-j][a-j][a-j][a-j][1-2]abcdefghijklmnopqrstuvwxy
SLOW_OPTS = [a-j][a-j][a-j][a-j][a-j][1-5]abcdefghijklmnopqrstuvwxy
