TOP = ../..
include $(TOP)/mk/boilerplate.mk

SSUBDIRS = \
  BinaryTrees ChameneosRedux Fannkuch Mandelbrot \
  Nbody Pidigits SpectralNorm
  
SUBDIRS = $(filter-out $(NOT_THESE), $(SSUBDIRS))

include $(TOP)/mk/target.mk


