TOP = ../../..
PROG = gamteb
SRCS = Consts.hs GamtebType.hs Distance.hs InitTable.hs Utils.hs Pair.hs \
       PhotoElec.hs RoulSplit.hs Compton.hs TransPort.hs Output.hs \
       GamtebMain.hs Main.hs
include $(TOP)/nofib/mk/nofib.mk
