TOP = ../../../..
PROG = andy_cherry
SRCS = DataTypes.lhs GenUtils.lhs Interp.lhs InterpUtils.lhs \
       Parser.lhs PrintTEX.lhs Main.lhs 
EXTRA_RUNTESTFLAGS = -d tex mygames.pgn
include $(TOP)/nofib/mk/nofib.mk
