TOP = ../..
include $(TOP)/mk/boilerplate.mk
SUBDIRS = SumSquare

# Covered by flag instead:
#   SumSquare-Explicit
# Worthless benchmark, runs too fast:
#   SumSquare-LazySum

include $(TOP)/mk/target.mk
