TOP = ../../..
PROG = reptile
SRCS = Diff.hs Mgrfuns.hs Drawfuns.hs Geomfuns.hs Layout.hs \
       Interstate.hs Tilefuns.hs Help.hs Rational.hs Auxprogfuns.hs \
       Psfuns.hs Progfuns.hs Main.hs 
include $(TOP)/nofib/mk/nofib.mk
