.TH HASHMD4 1 LOCAL
.SH NAME
hashmd4 \- add a MD4 hash to a Usenet article
.SH SYNOPSIS
.B hashmd4
[
.B \-n
] [
.I input
]
.SH DESCRIPTION
This program is used to apply an MD4 digest, or fingerprint, on an article 
intended to be posted to USENET.
.I Hashmd4
adds the X-Md4-Signature: header to the article. The header contains 
the article's MD4 signature value that will be checked by 
.IR checkmd4 
to determine if the article is intact. 
.I Hashmd4
calls
.IR md4
(See RFC1186) to generate a one-way hash signature for the article.
.PP
If a file is named on the command line, then
.I hashmd4
will overwrite the named file after inserting the md4 hashcode.
If no file is named, the program will read the article from standard
input, and write the new article on standard output; this makes it
convenient to do ``:%!hashmd4'' from
.IR vi (1)
just before exiting the editor with your article in it.
.PP
By default,
.I hashmd4
will try to read the file ``.signature'' in your home directory and
append it to the article.
It tries to simulate the actions of B2.11
.IR inews (8).
To suppress this check (for example, if you append your own signature),
use the ``\-n'' flag.
The header that hashmd4 puts on an article is of the form
.IP
X-Md4-Signature: value
.SH WARNING
.I Hashmd4
usage will only prove if an article has or has no been tampered with. It
does not provide any authentication.
.SH AUTHOR
.nf
Originally written as hashnews for snefru by Rich Salz <rsalz@bbn.com>
Hacked into hashmd4 by Kent Landfield <kent@sparky.imd.sterling.com>
.fi
.SH "SEE ALSO"
checkmd4(1L), RFC1186.
