TOP = ../..
include $(TOP)/mk/boilerplate.mk
-include opts.mk
include $(TOP)/mk/target.mk

FAST_OPTS = 27 16 8
NORM_OPTS = 24 16 8
SLOW_OPTS = 33 17 8

# Goes off to infinity with +VE information even if rollback is off
SRC_SUPERCOMP_HC_OPTS = -fsupercompiler-no-positive-information
