TOP = ../../..
include $(TOP)/mk/boilerplate.mk

SRC_HC_OPTS += -cpp -fglasgow-exts

FAST_OPTS = 400000
NORM_OPTS = 4000000 +RTS -K60M -RTS
SLOW_OPTS = 4000000 +RTS -K60M -RTS

include $(TOP)/mk/target.mk

