TOP = ../../..
PROG = infer
SRCS = MyList.hs Shows.hs Parse.hs Maybe.hs StateX.hs \
       Type.hs Term.hs FiniteMap.hs Substitution.hs Environment.hs \
       InferMonad.hs Infer.hs Main.hs
include $(TOP)/nofib/mk/nofib.mk
