TOP = ../../..
PROG = fem
SRCS = Basics.hs Vector.hs Matrix.hs VBmatrix.hs VBlldecomp.hs \
       Database.hs DB_interface.hs Degrees.hs Assemble_loadvec.hs \
       Pre_assemble.hs Elemstif.hs Assemble_stiffness.hs Displacement.hs \
       Elemforce.hs PrintSource.hs Printuvwforce.hs Main.hs
include $(TOP)/nofib/mk/nofib.mk
