#! /bin/sh

for f in *.scm
do
  b=`basename $f .scm`
  mv $b.txt $b.tst
done

for f in *.lsp
do
  b=`basename $f .lsp`
  mv $b.txt $b.tst
done

for f in *.sch
do
  b=`basename $f .sch`
  mv $b.txt $b.tst
done
