TOP = ../../..
PROG = fluid
SRCS = Norm.hs S_Array.hs Defs.hs Input_proc.hs Elefac.hs S_matrix.hs \
       Asb_routs.hs C_matrix.hs L_matrix.hs Rhs_Asb_routs.hs Min_degree.hs \
       Chl_routs.hs Chl_decomp.hs Chl_method.hs Tol_cal.hs Jcb_method.hs \
       TG_iter.hs Main.hs
EXTRA_RUNTESTFLAGS = -o1 fluid.stdout2 -o1 fluid.stdout3
include $(TOP)/nofib/mk/nofib.mk
