# -----------------------------------------------------------------------------
# $Id: Makefile,v 1.1 2001/03/02 11:44:24 simonmar Exp $

TOP = ../..
include $(TOP)/mk/boilerplate.mk
-include opts.mk
include $(TOP)/mk/target.mk
