TOP = ../../..
PROG = fulsom
SRCS = Interval.hs Types.hs Matrix.hs Csg.hs Kolor.hs Vector.hs \
       Oct.hs Quad.hs Raster.hs Shapes.hs Patchlevel.hs Fulsom.hs
EXTRA_RUNTESTFLAGS = 7
include $(TOP)/nofib/mk/nofib.mk
