TOP = ../..
include $(TOP)/mk/boilerplate.mk
-include opts.mk

# Seems to be a real memory hog, this one
EXTRA_RUNTEST_OPTS = +RTS -M100m -RTS

include $(TOP)/mk/target.mk


NORM_OPTS = 20000
SLOW_OPTS = 51000
