TOP = ../..
include $(TOP)/mk/boilerplate.mk
-include opts.mk

# Seems to be a real memory hog, this one
SRC_RUNTEST_OPTS += +RTS -M300m -RTS

include $(TOP)/mk/target.mk

FAST_OPTS =  8000
NORM_OPTS = 80000
SLOW_OPTS = 80000
