TOP = ..
include $(TOP)/mk/boilerplate.mk

# SLPJ subset
# SUBDIRS = \
#  expert gcd hartel knights mandel mandel2 \
#  minimax multiplier simple 

SUBDIRS = \
  ansi awards banner boyer boyer2 calendar cichelli circsim clausify cse \
  eliza expert fibheaps fish fft2 gcd hartel life knights mandel mandel2 \
  minimax multiplier pretty primetest rewrite scc simple sorting treejoin power \
  constraints cryptarithm1 cryptarithm2 para puzzle salishan sphere 

# compreals	no suitable test data

include $(TOP)/mk/target.mk


