TOP = ..
include $(TOP)/mk/boilerplate.mk

# SLPJ subset
# SUBDIRS = \
#  expert gcd hartel knights mandel mandel2 \
#  minimax multiplier simple 

SUBDIRS = \
  ansi awards banner boyer boyer2 calendar cichelli circsim clausify \
  constraints cryptarithm1 cryptarithm2 cse eliza expert fibheaps fish \
  fft2 gcd hartel life knights mandel mandel2 minimax multiplier para \
  power pretty primetest puzzle rewrite scc simple sorting sphere treejoin

# compreals	no suitable test data
# salishan	no Makefile

include $(TOP)/mk/target.mk


