# Simple makefile for compress
#
# make doc		- makes report
# make HC={glhc|hbc}	- makes compress with glhc or hbc

none:
	@echo No target specified.

compress:
	make -f Makefile.${HC} compress

clean:
	mv LMLbitops.hi LMLbitops.tmp
	rm *.o *.hi compress
	mv LMLbitops.tmp LMLbitops.hi

doc:
	latex Main.tex
	dvips Main > Main.ps

dist:
	shar *.hs LMLbitops.hi Make* > lzwc.sh
