TOP = ../../..
PROG = compress2
SRCS = Encode.hs WriteRoutines.hs Main.hs
EXTRA_HCFLAGS = -fglasgow-exts
EXTRA_RUNTESTFLAGS = -i ../../spectral/hartel/listcompr/listcompr.stdout
include $(TOP)/nofib/mk/nofib.mk
