TOP = ../..
include $(TOP)/mk/boilerplate.mk
SUBDIRS = AccumulatingParam-Peano AccumulatingParam Ackermann AckermannPeano-1 AckermannPeano-2 EvenDouble EvenDoubleGenerator Generalisation KMP LetRec MapMapFusion ReverseReverse queens-explicit
# Covered by Peter somewhat already:
#   AppendAssociativity
# Covered by other benchmarks:
#   FoldlSpecialisation Generalisation-Lazy Generalisation-Literals-Lazy (AccumulatingParam-*)
#   StrictFoldlSpecialisation (Generalisation)
# Just boring:
#   SpeculationWorstCase
#   AppendRightUnit
#   Generalisation-Literals

include $(TOP)/mk/target.mk
