TOP = ../../../..
PROG = nucleic2
SRCS = Types.hs RA.hs RC.hs RG.hs RU.hs Main.hs
EXTRA_RUNTESTFLAGS = -o1 nucleic2.stdout1 -o1 nucleic2.stdout2
EXTRA_HCFLAGS += -cpp -fglasgow-exts
include $(TOP)/nofib/mk/nofib.mk
