TOP = ../../..
PROG = veritas
SRCS = Core_datatype.hs Vtslib.hs Sub_Core1.hs Sub_Core2.hs \
       Sub_Core3.hs Sub_Core4.hs Dcore.hs Core_database.hs Kernel.hs \
       Lookup.hs Type_defs.lhs Token.lhs Edlib.lhs X_interface.hs \
       Tree.hs Getops.hs Attributes.lhs Unparse.lhs Build_Tm.lhs \
       Build_itrm.lhs Parse.lhs DerivedRules.hs Tags.hs Globals.hs \
       Goals.hs Display.hs Tactics.hs Auto.hs Tacticals.hs Editor.hs \
       ThmTactics.hs Main.hs
include $(TOP)/nofib/mk/nofib.mk
